### ISSUE TITLE
OTP 27 support

### ISSUE THREAD

**Issue by MarkoMin** [WhatsApp/tree-sitter-erlang#6]
Are there plans to support new stuff added in OTP 27:
1. `-moduledoc` and `-doc` attributes
2. Sigils
3. Triple quoted strings

?

**Comment by michalmuskala** [comment]
It should be already supported since version 0.7.0 released July 12. Is there any code in particular that you've found that's not properly supported?

cc @alanz

**Comment by MarkoMin** [comment]
Ah, my fault, I didn't update `nvim-treesitter` properly, sorry... Anyways, there are some errors with building newer versions of `nvim-tree-sitter` that include `tree-sitter-erlang >= 0.7.0` so I can't confirm that everything works for me, but I'll close the issue.

**Comment by codeadict** [comment]
Any plans to add highlight queries for these, like the Elixir ones?
